apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eg-api
  template:
    metadata:
      labels:
        app: eg-api
    spec:
      containers:
      - name: eg-api
        image: docker.io/${DOCKER_USERNAME}/eg-api:${GITHUB_SHA}
        command: ["/prod/go-events-guard", "server"]
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health 
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
