name: Deploy Golang Events-guard App to Kubernetes

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del codi
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up the golang environment
    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.23' # Adjust Go version as required

    # 3. Install GO offs
    - name: Install Go dependencies
      run: |
        go mod download

    # 4. Compilate the Golang application
    - name: Build Golang app
      run: |
        go build -o events-guard .

    # 5. Create and upload the Docker image with the Golang application
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 6. Check if Docker image exists
    - name: Check Docker image exists
      id: check-image
      run: |
        if docker pull ${{ secrets.DOCKER_USERNAME }}/eg-api:${{ github.sha }}; then
          echo "Image exists"
          echo "::set-output name=image_exists::true"
        else
          echo "Image does not exist"
          echo "::set-output name=image_exists::false"
        fi

    # 7. Build and push Docker image if it doesn't exist
    - name: Build and Push Docker image
      if: steps.check-image.outputs.image_exists == 'false'
      run: |
        TAG=${{ github.sha }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/eg-api:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/eg-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/eg-api:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/eg-api:latest

    # 8. Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # 9. Configure Kubernetes
    - name: Configure Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml

    # 10. Replace variables in manifests
    - name: Replace variables in manifests
      uses: franzbischoff/replace_envs@v1
      with:
        from_file: 'k3s/eg-api-deploy.yaml'
        to_file: 'k3s/eg-api-deploy.yaml'
        commit: 'false'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        TAG: ${{ github.sha }}

    # 11. Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        KUBECONFIG=kubeconfig.yaml kubectl apply -f k3s/eg-api-deploy.yaml
        KUBECONFIG=kubeconfig.yaml kubectl apply -f k3s/eg-api-service.yaml